---
# tasks file for vector-role
- name: Download vector
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.12.2/vector-0.12.2-1.x86_64.rpm"
    dest: "./vector-0.12.2.rpm"
- name: Install vector
  ansible.builtin.yum:
    name:
      - vector-0.12.2.rpm
    state: present
